# Example anonymizer configuration file

nthreads: 2
input_dir_path: "./output/parser/dataset/"
output_dir_path: "./output/anonymizer/"
# (optional, run with all found lists by default)
# lists_to_anonymize: []
